title: Configuration
data:
  navigation_content:
    -
      type: paragraph
      content:
        -
          type: text
          text: 'Veel mensen denken onterecht dat het openzetten van de Groningse gaskraan alle huidige energieproblemen oplost. Men baseert zich echter niet op de feiten. Er wordt veel geroepen en weinig tot geen rekening gehouden met de veiligheid van Groningers. '
    -
      type: paragraph
      content:
        -
          type: text
          text: 'Jouke, Lisa en Rob willen graag de juiste informatie vertellen. '
  error_404_entry: 059d4d8d-fc60-49f8-8823-7da10549e84e
  copyright_since: 2022
  copyright_name: 'Merkactivisten & Studio 1902'
  privacy_statement_type: none
