title: Configuration
data:
  navigation_content:
    -
      type: paragraph
      content:
        -
          type: text
          text: 'Informatie over dit project. Waarom is het nodig, wat kun jij doen.'
    -
      type: paragraph
      content:
        -
          type: text
          text: 'Wie droeg er aan bij, Merkactivisten en Studio1902 en naam van alle andere toppers.'
  error_404_entry: 059d4d8d-fc60-49f8-8823-7da10549e84e
  copyright_since: 2022
  copyright_name: 'Merkactivisten & Studio 1902'
  privacy_statement_type: none
